build:
  maxIssues: 0
  excludeCorrectable: false
  weights:

config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false

processors:
  active: true

console-reports:
  active: true

output-reports:
  active: true

comments:
  active: true
  CommentOverPrivateFunction:
    active: false
  CommentOverPrivateProperty:
    active: false
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false

complexity:
  active: true
  ComplexCondition:
    active: true
    threshold: 4
  ComplexInterface:
    active: false
  LongMethod:
    active: true
    threshold: 60
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 7
  TooManyFunctions:
    active: true
    thresholdInFiles: 15
    thresholdInClasses: 15
    thresholdInInterfaces: 15
    thresholdInObjects: 15
    thresholdInEnums: 15

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: false
  SuspendFunWithFlowReturnType:
    active: false

empty-blocks:
  active: true

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - ArrayIndexOutOfBoundsException
      - Error
      - Exception
      - IllegalMonitorStateException
      - IndexOutOfBoundsException
      - NullPointerException
      - RuntimeException
      - Throwable

naming:
  active: true
  FunctionNaming:
    active: true
    functionPattern: '[a-z][a-zA-Z0-9]*|`.*`'
  ClassNaming:
    active: true
    classPattern: '[A-Z][a-zA-Z0-9]*'
  VariableNaming:
    active: true
    variablePattern: '[a-z][a-zA-Z0-9]*'

performance:
  active: true
  SpreadOperator:
    active: false

potential-bugs:
  active: true
  UnsafeCast:
    active: false

style:
  active: true
  MagicNumber:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 120
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: false
  ReturnCount:
    active: true
    max: 3
  UnusedPrivateMember:
    active: true